import mongoose from "mongoose";

const qrcodeSchema = new mongoose.Schema(
  {
    user: { 
      type: mongoose.Schema.Types.ObjectId, 
      ref: "User", 
      required: true 
    },
    tableId: { 
      type: String, 
      required: false, // Will be auto-generated by pre-save hook
      trim: true,
      unique: true
    },
    tableName: { 
      type: String, 
      required: true, 
      trim: true 
    },
    qrCodeUrl: { 
      type: String, 
      default: "" 
    },
    isActive: { 
      type: Boolean, 
      default: true 
    },
  },
  { timestamps: true }
);

// Generate unique tableId before saving
qrcodeSchema.pre("save", async function(next) {
  if (!this.tableId) {
    // Generate a unique table ID using MongoDB ObjectId converted to string
    // This ensures uniqueness without needing to check the database
    const objectId = new mongoose.Types.ObjectId();
    this.tableId = `TBL-${objectId.toString()}`;
  }
  next();
});

export default mongoose.model("QRCode", qrcodeSchema);

